// Build step: decode an Atari 8x8 font PNG (256x32, 128 glyphs in internal-code
// order, 32 per row) into js/anticfont.js  ->  ATARI_FONT[code] = [8 bytes].
// Uses Chrome (via Playwright) canvas getImageData for robust PNG decoding.
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const SRC = 'C:/repo/github/ByPS/boulder-dash-js/resources/EightBit-Atari-Fonts-2/Original Bitmaps/STANDARD.png';
const OUT = path.resolve(__dirname, '..', 'js', 'anticfont.js');

(async () => {
  const b64 = fs.readFileSync(SRC).toString('base64');
  const browser = await chromium.launch({ channel: 'chrome' });
  const page = await browser.newPage();

  const glyphs = await page.evaluate(async (dataUrl) => {
    const img = new Image();
    img.src = dataUrl;
    await img.decode();
    const W = img.width, H = img.height;          // expect 256 x 32
    const cv = document.createElement('canvas');
    cv.width = W; cv.height = H;
    const ctx = cv.getContext('2d');
    ctx.drawImage(img, 0, 0);
    const px = ctx.getImageData(0, 0, W, H).data;
    const lum = (x, y) => { const i = (y * W + x) * 4; return (px[i] + px[i + 1] + px[i + 2]) / 3; };

    // decide ink: sample average; ink = the minority/brighter set. Use >128 as ink.
    const perRow = W / 8;                          // 32 glyphs per row
    const out = [];
    for (let n = 0; n < 128; n++) {
      const gx = (n % perRow) * 8, gy = Math.floor(n / perRow) * 8;
      const rows = [];
      for (let r = 0; r < 8; r++) {
        let byte = 0;
        for (let c = 0; c < 8; c++) if (lum(gx + c, gy + r) > 128) byte |= (0x80 >> c);
        rows.push(byte);
      }
      out.push(rows);
    }
    return { out, W, H };
  }, 'data:image/png;base64,' + b64);

  await browser.close();

  const F = glyphs.out;
  // sanity: render a few known internal codes as ASCII art
  const art = (code) => F[code].map(b => Array.from({ length: 8 }, (_, i) => (b & (0x80 >> i)) ? '#' : '.').join('')).join('\n');
  console.log('image', glyphs.W + 'x' + glyphs.H);
  console.log('space ($00) all-zero:', F[0].every(b => b === 0));
  console.log("glyph $21 ('A'):\n" + art(0x21));
  console.log("glyph $28 ('H'):\n" + art(0x28));
  console.log("glyph $65 ('e' lowercase):\n" + art(0x65));
  console.log("glyph $6F ('o' lowercase):\n" + art(0x6F));

  const body = 'const ATARI_FONT = [\n' +
    F.map((g, n) => '  [' + g.map(b => '0x' + b.toString(16).toUpperCase().padStart(2, '0')).join(',') + '], // $' + n.toString(16).toUpperCase().padStart(2, '0')).join('\n') +
    '\n];\n';
  fs.writeFileSync(OUT, '// Atari 8x8 font (internal-code order) baked from ' + path.basename(SRC) + '. Generated by test/buildfont.js.\n' + body);
  console.log('wrote', OUT);
})();
